services:
  - type: web
    name: welding-inspection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env:
      - key: SECRET_KEY
        from: env
